# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once = sparkle --replace -d
exec-once = ab-download-manager --replace -d
# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 26