# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
# 系统工具类

windowrulev2 = float, title:rofi.*
windowrulev2 = float, title:Lutris
windowrulev2 = float, title:QQ
windowrulev2 = float, title:*.dolphin
windowrulev2 = float, title:图片查看器